### ISSUE TITLE
dots break the world

### ISSUE THREAD

**Issue by zeke** [npm/docs#135] opened 2015-04-03 21:32 UTC
https://docs.npmjs.com/files/.npmignore

> RangeError: Maximum call stack size exceeded

Original issue: https://github.com/npm/newww/issues/808

**Comment by ashleygwilliams** [comment] 2015-10-21 22:08
can't find where this is linked to. any idea? trying to replicate.

**Comment by ashleygwilliams** [comment] 2015-12-28 17:41
can't reproduce, seems to work fine. closing.

**Closed by ashleygwilliams** 2015-12-28 17:41 UTC
Labels: bug
