### ISSUE TITLE
Missing page >>> npm-rm

### ISSUE THREAD

**Issue by Stephn-R** [npm/docs#468] opened 2015-11-24 15:51 UTC
This is the missing page: https://docs.npmjs.com/cli/rm

I accessed it through the link on the bottom of this page: https://docs.npmjs.com/files/package.json

**Comment by KenanY** [comment] 2015-11-26 17:57
Duplicate of https://github.com/npm/docs/issues/452, and fixed by https://github.com/npm/npm/pull/10419 (just needs to be deployed I think).

**Comment by ashleygwilliams** [comment] 2015-12-04 17:03
closing, as it is a dupe.

**Closed by ashleygwilliams** 2015-12-04 17:03 UTC
Labels: bug, CLI, content, duplicate
